services:
  hr-projectmanagement-db:
    image: postgres:15
    container_name: Hr_PM_pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ProjectManagement
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  hr.projectmanagement:
    image: ${DOCKER_REGISTRY-}hrprojectmanagement
    build:
      context: .
      dockerfile: HR.ProjectManagement/Dockerfile
    depends_on:
      hr-projectmanagement-db:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__ApplicationDatabaseConnectionString=Server=hr-projectmanagement-db;Port=5432;Database=ProjectManagement;User Id=postgres;Password=postgres;Include Error Detail=true
    ports:
      - "6000:8080"
      - "6001:8081"

volumes:
  postgres-data:
